version: '3'

services:
    app:
        build: ./
        container_name: microservice-videos-app
        image: fullcycle/php
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-php
    
    nginx:
        image: nginx:1.15.0-alpine
        container_name: microservice-videos-nginx
        ports:
            - "8880:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-php

networks:
    app-php:
        driver: bridge
